# Use root/example as user/password credentials
version: '3.1'

services:

  # Mongo DB
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example

  # Mongo DB web administration console
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  # Go application service
  go-service:
    build: .
    image: tstuchel/go-service
    restart: always
    ports:
      - 8090:8090
    environment:
      APP_PORT: 8090
      JWT_SECRET: SuperSecretTokenToSignJWT
      DB_URI: mongodb://mongo:27017
      DB_NAME: go-service
