// Code generated by counterfeiter. DO NOT EDIT.
package customerfakes

import (
	"github.com/TStuchel/go-service/customer"
	"net/http"
	"sync"
)

type FakeCustomerController struct {
	GetCustomerStub        func(http.ResponseWriter, *http.Request)
	getCustomerMutex       sync.RWMutex
	getCustomerArgsForCall []struct {
		arg1 http.ResponseWriter
		arg2 *http.Request
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCustomerController) GetCustomer(arg1 http.ResponseWriter, arg2 *http.Request) {
	fake.getCustomerMutex.Lock()
	fake.getCustomerArgsForCall = append(fake.getCustomerArgsForCall, struct {
		arg1 http.ResponseWriter
		arg2 *http.Request
	}{arg1, arg2})
	fake.recordInvocation("GetCustomer", []interface{}{arg1, arg2})
	fake.getCustomerMutex.Unlock()
	if fake.GetCustomerStub != nil {
		fake.GetCustomerStub(arg1, arg2)
	}
}

func (fake *FakeCustomerController) GetCustomerCallCount() int {
	fake.getCustomerMutex.RLock()
	defer fake.getCustomerMutex.RUnlock()
	return len(fake.getCustomerArgsForCall)
}

func (fake *FakeCustomerController) GetCustomerCalls(stub func(http.ResponseWriter, *http.Request)) {
	fake.getCustomerMutex.Lock()
	defer fake.getCustomerMutex.Unlock()
	fake.GetCustomerStub = stub
}

func (fake *FakeCustomerController) GetCustomerArgsForCall(i int) (http.ResponseWriter, *http.Request) {
	fake.getCustomerMutex.RLock()
	defer fake.getCustomerMutex.RUnlock()
	argsForCall := fake.getCustomerArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeCustomerController) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getCustomerMutex.RLock()
	defer fake.getCustomerMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeCustomerController) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ customer.CustomerController = new(FakeCustomerController)
